name: Build

on:
  - push

jobs:
  build-files:
    runs-on: ubuntu-latest
    container: jamieleecho/coco-dev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build c10 and dsk files
        run: make all
